spring:
  data:
    elasticsearch:
      # 节点名称，默认为 elasticsearch
      cluster-name: elasticsearch
      # 节点地址，多个几点用逗号隔开
      cluster-nodes: 127.0.0.1:9300
      #是否开启本地存储
      repositories:
        enabled: true
      #设置连接超时
#      properties:
#        transport:
#          tcp:
#            connect_timeout: 120s

# 端口设置
server:
  port: 8089